# baseURL = "file:///Users/kuniatsu/Dropbox/hugo/kuraseru/public"
# baseURL = "https://kuniatsu.github.io/kuraseru/"
canonifyurls = true
relativeurls = true
languageCode = "en-us"
title = "KURASERU"
theme = "hugo-terrassa-theme"
publishDir = "docs"
