baseURL = "https://kuniatsu.github.io/kuraseru/."
canonifyurls = true
languageCode = "en-us"
title = "KURASERU"
//theme = "hugo-terrassa-theme"
theme = "terrassa"
//publishDir = "docs"
publishDir = "public"